version: '2'
services:
  web:
    container_name: valoration
    build: .
    ports:
      - ${SINATRA_DEFAULT_PORT}:${SINATRA_DEFAULT_PORT}
    volumes:
     - .:/opt/valoration
     - bundle:/usr/local/bundle

    links:
      - selenium
    command: bundle exec rake

  selenium:
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    container_name: valoration-chrome-browser
    logging:
      driver: none

volumes:
  bundle:
    driver: local
